AZIENDA: 1
ANNOESE: 2012
ANARIF: 9
ANAGEN:
  TIPO SOGGETTO:
    F: 'Persona fisica'
    G: 'Persona giuridica'
    I: 'Ditta individuale'  
ANAIND:
  NRMAG:
    0: 'Nessun magazzino'
    1: 'Magazzino 1'
    2: 'Magazzino 2'
    3: 'Magazzino 3'
    4: 'Magazzino 4'
    5: 'Magazzino 5'

CAUSMAG:
  TIPO_DOC:
    0: 'Gruppo generico'
    1: 'Gruppo ddt'
    2: 'Gruppo contabile'
    3: 'Gruppo tre'
    4: 'Gruppo quattro'
  TIPO:
    E: 'Entrata'
    U: 'Uscita'
    T: 'Trasferimento'
  MOVIMPMAG:
    M: 'Movimenta Mag.'
    I: 'Impegna Mag.'
    N: 'Nessun impatto Mag.'
  MAGCLI:
    C: 'Carico'
    S: 'Scarico'
    N: 'Nessuna'
  CONTABILE:
    S: 'Si'
    N: 'No'
CONTO:
  TIPOCONTO:
    C: 'Cliente__'
    F: 'Fornitore'
    A: 'Altro____'
  TIPOPEO:
    P: 'Patrimoniale'
    E: 'Economico'
    O: 'd''Ordine'
PAESE:
  TPEU:
    E: 'Europeo'
    X: 'Extraeuropeo'
    N: 'Da assegnare'
TESDOC:
  SEGUEFATT:
    S: 'Si'
    N: 'No'
RIGDOC:
  PATHXLS: 'C:'
  FILEXLS: 'C:'
CAUSALE:
  TIPOREG:
    S: 'Si'
    N: 'No'
  TIPOIVA:
    S: 'Si'
    N: 'No'
