ELNCAZND:
  9: EIFIS EDITORE
  105: FIERE ED EVENTI
ANAGEN:
  TIPO_SOGGETTO:
    F: 'Pers.fisica'
    G: 'Pers.giuridica'
    I: 'Ditta individ.'
    E: 'Ente statale'
    S: 'Studente'
    D: 'Docente'
    B: 'Business'
    P: 'Personal'

  TIPO_SOCIAL:
    LK: 'LinkedIn'
    IG: 'Instagram'
    FB: 'Facebook'
    TW: 'Twitter'
    TG: 'Telegram'
    WA: 'Watsapp'
    XI: 'Xing'
    SN: 'SnapChat'
    TU: 'Tumblir'
    TO: 'Twoo'
    DI: 'Disqus'
    GP: 'Google+'
    RE: 'Renren'
    PI: 'Pinterest'
    YU: 'YouTube'
    VI: 'Vine'
    MU: 'Meetup'
    ME: 'Medium'
    RE: 'Reddit'
    GH: 'GitHub'
    GL: 'GitLab'
    SO: 'StackOverflow'

ANAIND:
  NRMAG:
    0: 'No'
    1: 'Princ'
    2: 'Sec01'
    3: 'Sec02'
    4: 'Sec03'
    5: 'Sec04'
    6: 'Sec05'
    7: 'Sec06'
    8: 'Sec07'
    9: 'Sec08'
    10: 'Sec09'
    11: 'Sec10'
    12: 'Sec11'
    13: 'Sec12'
    14: 'Sec13'
    15: 'Sec14'
    16: 'Sec15'
    17: 'Sec16'
    18: 'Sec17'
    19: 'Sec18'
    20: 'Sec19'
    21: 'Sec20'
CAUSMAG:
  TIPO_DOC:
    0: 'Doc.Contabili'
    1: 'Doc.Trasporto'
  TIPO:
    E: 'Entrata'
    U: 'Uscita'
    T: 'Trasf.'
    V: 'Rnd.Vnd.'
    R: 'Rnd.Resi'
  MOVIMPMAG:
    M: 'Movimenta'
    I: 'Impegna'
    N: 'Nessuna'
  MAGCLI:
    C: 'Car'
    S: 'Sca'
    N: 'No'
  CONTABILE:
    S: 'Si'
    N: 'No'
CONTO:
  TIPOCONTO:
    C: 'Cliente'
    F: 'Fornitore'
    A: 'Altro'
  TIPOPEO:
    P: 'Patrim'
    E: 'Econom'
    O: 'Ordine'
PAESE:
  TPEU:
    E: 'Europeo'
    X: 'Extraeu'
    N: 'Da ass.'
    W: 'Mondo'
TESDOC:
  SEGUEFATT:
    S: 'Si'
    N: 'No'
CAUSALE:
  TIPOREG:
    S: 'Si'
    N: 'No'
  TIPOIVA:
    S: 'Si'
    N: 'No'
SCADENZA:
  TIPO:
    RB: 'Ri.Ba.'
    RD: 'Rim.Diretta'
  STATO:
    A: 'Attiva'
    S: 'Scaduta/Insoluta'
    P: 'Pagata'
COSTO:
  STATO:
    RF: 'A ricevimento fattura'
    FA: 'Fatturato'
    CA: 'Pagato per cassa'
    DD: 'Da definire'
  TIPO_SPE:
    G: 'GLS'
    P: 'Poste'
SPEDIZ:
  CAUSTRA:
    ICD: 'C/Deposito'
    ICV: 'C/Vendita'
    IOM: 'Omaggio'
    RCD: 'Reso da C/Dep'
    RCV: 'Reso da C/Ven'
  CORRIERE:
    GLS: 'GLS'
    SDA: 'SDA'
    BRT: 'BARTOLINI'
    PIT: 'POSTE ITALIANE'
    MTT: 'MITTENTE'
    DST: 'DESTINATARIO'
    NEX: 'NEXIVE'
    CBT: 'COMBITRAS'
  ASPETTO:
    BST: 'BUSTE'
    CRT: 'CARTONI'
    VSB: 'VISIBILE'
  PORTO:
    ASS: 'Assegnato'
    FRC: 'Franco'
    CTR: 'Contrassegno'
  UM:
    KG: 'Chilogrammi'
    NR: 'Numero'
    PZ: 'Pezzi'
    MT: 'Metri lineari'
    MQ: 'Metri quadrati'
    ML: 'Millilitri'
ARTICLE:
  CATEG:
    GE: 'Generica'
    LB: 'Libri'
    CD: 'CD'
    PE: 'Periodici'
    SV: 'Servizi'
CONF:
  INSANA:
    S: 'Si'
    N: 'No'
  INSIND:
    S: 'Si'
    N: 'No'
  INSART:
    S: 'Si'
    N: 'No'
  CODERIGDOC:
    S: 'Si'
    N: 'No'
