ELNCAZND:
  9: EIFIS EDITORE
ANAGEN:
  TIPO_SOGGETTO:
    F: 'Pers.fisica'
    G: 'Pers.giuridica'
    I: 'Ditta individ.'
ANAIND:
  NRMAG:
    0: 'No'
    1: 'Princ'
    2: 'Sec1'
    3: 'Sec2'
    4: 'Sec3'
CAUSMAG:
  TIPO_DOC:
    0: 'Doc.Contabili'
    1: 'Doc.Trasporto'
    2: 'Doc.Generici'
  TIPO:
    E: 'Entrata'
    U: 'Uscita'
    T: 'Trasf.'
    V: 'Rnd.Vnd.'
    R: 'Rnd.Resi'
  MOVIMPMAG:
    M: 'Movimenta'
    I: 'Impegna'
    N: 'Nessuna'
  MAGCLI:
    C: 'Car'
    S: 'Sca'
    N: 'No'
  CONTABILE:
    S: 'Si'
    N: 'No'
CONTO:
  TIPOCONTO:
    C: 'Cliente'
    F: 'Fornitore'
    A: 'Altro'
  TIPOPEO:
    P: 'Patrim'
    E: 'Econom'
    O: 'Ordine'
PAESE:
  TPEU:
    E: 'Europeo'
    X: 'Extraeu'
    N: 'Da ass.'
TESDOC:
  SEGUEFATT:
    S: 'Si'
    N: 'No'
CAUSALE:
  TIPOREG:
    S: 'Si'
    N: 'No'
  TIPOIVA:
    S: 'Si'
    N: 'No'
SPEDIZ:
  CAUSTRA:
    ICD: 'C/Deposito'
    ICV: 'C/Vendita'
    IOM: 'Omaggio'
    RCD: 'Reso da C/Dep'
    RCV: 'Reso da C/Ven'
  CORRIERE:
    GLS: 'GLS'
    SDA: 'SDA'
    BRT: 'BARTOLINI'
    PIT: 'POSTE ITALIANE'
    MTT: 'MITTENTE'
    DST: 'DESTINATARIO'
  ASPETTO:
    BST: 'BUSTE'
    CRT: 'CARTONI'
    VSB: 'VISIBILE'
  PORTO:
    ASS: 'Assegnato'
    FRC: 'Franco'
    CTR: 'Contrassegno'
  UM:
    KG: 'Chilogrammi'
    NR: 'Numero'
    PZ: 'Pezzi'
    MT: 'Metri lineari'
    MQ: 'Metri quadrati'
ARTICLE:
  CATEG:
    GE: 'Generica'
    LB: 'Libri'
    CD: 'CD'
    PE: 'Periodici'