ELNCAZND:
  9: EIFIS EDITORE
ANAGEN:
  TIPO SOGGETTO:
    F: 'Persona fisica'
    G: 'Persona giuridica'
    I: 'Ditta individuale'
ANAIND:
  NRMAG:
    0: 'Nessuno'
    1: 'Principale'
    2: 'Secondario1'
    3: 'Secondario2'
    4: 'Secondario3'
CAUSMAG:
  TIPO_DOC:
    0: 'generico'
    1: 'ddt'
    2: 'contabile'
  TIPO:
    E: 'Entrata'
    U: 'Uscita'
    T: 'Trasferimento'
    V: 'Rend.Vendite'
    R: 'Rend.Resi'
  MOVIMPMAG:
    M: 'Movimenta'
    I: 'Impegna'
    N: 'Non impatta'
  MAGCLI:
    C: 'Carico'
    S: 'Scarico'
    N: 'Nessuna'
  CONTABILE:
    S: 'Si'
    N: 'No'
CONTO:
  TIPOCONTO:
    C: 'Cliente__'
    F: 'Fornitore'
    A: 'Altro____'
  TIPOPEO:
    P: 'Patrimoniale'
    E: 'Economico'
    O: 'd''Ordine'
PAESE:
  TPEU:
    E: 'Europeo'
    X: 'Extraeuropeo'
    N: 'Da assegnare'
TESDOC:
  SEGUEFATT:
    S: 'Si'
    N: 'No'
CAUSALE:
  TIPOREG:
    S: 'Si'
    N: 'No'
  TIPOIVA:
    S: 'Si'
    N: 'No'
SPEDIZ:
  CAUSTRA:
    ICD: 'Conto Deposito'
    ICV: 'Conto Vendita'
    IOM: 'Omaggio'
    RCD: 'Reso da Conto Deposito'
    RCV: 'Reso da Conto Vendita'
  CORRIERE:
    GLS: 'GLS'
    SDA: 'SDA'
    BRT: 'BARTOLINI'
  ASPETTO:
    CRT: 'CARTONI'
    VSB: 'VISIBILE'
  PORTO:
    ASS: 'Assegnato'
    FRC: 'Franco'
  UM:
    KG: 'Chilogrammi'
    NR: 'Numero'
    PZ: 'Pezzi'
    MT: 'Metri lineari'
    MQ: 'Metri quadrati'
